Add property info and value methods to TypeExtensions
AndcultureCode/AndcultureCode.CSharp.Extensions pull request #40
Opened 2020-09-21 19:42 UTC by mrjones2014

- [x] Related GitHub issue(s) linked in PR description
- [x] Destination branch merged, built and tested with your changes
- [x] Code formatted and follows best practices and patterns
- [x] Code builds cleanly (no _additional_ warnings or errors)
- [x] Manually tested
- [x] Automated tests are passing
- [x] No _decreases_ in automated test coverage
- [x] Documentation updated (readme, docs, comments, etc.)
- [x] Localization: No hard-coded error messages in code files (_minimally_ in string constants)

Fixes #35

2020-09-22 12:31 UTC, brandongregoryscott requested changes
Just some minor cleanup @mrjones2014 👍

2020-09-22 12:31 UTC, brandongregoryscott commented on src/AndcultureCode.CSharp.Extensions/TypeExtensions.cs
> +            if (!(src?.GetType().HasPublicProperty(propertyName) ?? false))
Consider pulling out the first expression into a variable (maybe `hasPublicProperty`) and then null/false checking it in the `if` block for readability

2020-09-22 12:31 UTC, brandongregoryscott commented on test/AndcultureCode.CSharp.Extensions.Tests/TypeExtensionsTests.cs
> +            public const string TEST_CONST_STRING = "TEST_CONST_STRING";
Nitpick - alphabetization

Does it handle protected properties?

2020-09-22 12:31 UTC, brandongregoryscott commented on test/AndcultureCode.CSharp.Extensions.Tests/TypeExtensionsTests.cs
> +            var randomizer = new Randomizer();
We could probably import the `AndcultureCode.CSharp.Testing` package (if not already added) and inherit from `BaseUnitTest` for the randomizer instance there.

2020-09-22 12:31 UTC, brandongregoryscott commented on test/AndcultureCode.CSharp.Extensions.Tests/TypeExtensionsTests.cs
> +        private class GetPublicPropertyValueTestStub
We could probably move this to the `Stubs` folder and keep it as a single class w/ the constructor that sets a value so we don't need a new private class for each test method

2020-09-22 17:28 UTC, mrjones2014 commented on test/AndcultureCode.CSharp.Extensions.Tests/TypeExtensionsTests.cs
> +            public const string TEST_CONST_STRING = "TEST_CONST_STRING";
@brandongregoryscott it only handles public properties. I figured if you're using these methods you probably only want to look at public properties.

2020-09-22 17:36 UTC, brandongregoryscott commented on test/AndcultureCode.CSharp.Extensions.Tests/TypeExtensionsTests.cs
> +            public const string TEST_CONST_STRING = "TEST_CONST_STRING";
Right - it might be worth adding a test or two to ensure protected properties aren't returned (similar to the private field test(s))

2020-09-22 17:40 UTC, brandongregoryscott reviewed
Left two comments @mrjones2014

2020-09-22 17:40 UTC, brandongregoryscott commented on src/AndcultureCode.CSharp.Extensions/TypeExtensions.cs
> +                return null;
Looks like codecov picked up this line change - should be a quick test to write

2020-09-22 17:40 UTC, brandongregoryscott commented on test/AndcultureCode.CSharp.Extensions.Tests/TypeExtensionsTests.cs
> +        private class HasPublicPropertyTestStub
Was this test class intentionally left in instead of using the generic `TypeExtensionsTestStub`?

2020-09-22 18:03 UTC, mrjones2014 commented on test/AndcultureCode.CSharp.Extensions.Tests/TypeExtensionsTests.cs
> +        private class HasPublicPropertyTestStub
nope, accidental. I'll remove it

2020-09-22 18:09 UTC, mrjones2014 commented
@brandongregoryscott all comments should be addressed now,

2020-09-22 18:57 UTC, brandongregoryscott approved these changes

2020-09-22 18:59 UTC, merged

2021-04-09 14:12 UTC, wintondeshong commented
@all-contributors please add @mrjones2014 for code and tests