Convenience method for safely getting types from an assembly
AndcultureCode/AndcultureCode.CSharp.Extensions pull request #46
Opened 2020-10-17 21:57 UTC by dzoccarato

- [x] Related GitHub issue(s) linked in PR description
- [x] Destination branch merged, built and tested with your changes
- [x] Code formatted and follows best practices and patterns
- [x] Code builds cleanly (no _additional_ warnings or errors)
- [x] Manually tested
- [x] Automated tests are passing
- [x] No _decreases_ in automated test coverage
- [x] Documentation updated (readme, docs, comments, etc.)
- [x] Localization: No hard-coded error messages in code files (_minimally_ in string constants)

Resolves #38

2020-10-20 12:52 UTC, wintondeshong requested changes
@dzoccarato thank you for this contribution! There are a few minor changes to be made and then we should be good to go 👍

2020-10-20 12:52 UTC, wintondeshong commented on src/AndcultureCode.CSharp.Extensions/AssemblyExtension.cs
> +            if(assembly == null)
Nitpick: Please wrap in curly braces `{}`; Also, space between `if` and `(`

2020-10-20 12:52 UTC, wintondeshong commented on test/AndcultureCode.CSharp.Extensions.Tests/AssemblyExtensionsTest.cs
> +        public void GetSafetlyTypes_Given_Empty_Type_With_Null_Assembly()
Suggestion: Believe test method name needs to state that it returns empty

2020-10-20 12:52 UTC, wintondeshong commented on test/AndcultureCode.CSharp.Extensions.Tests/AssemblyExtensionsTest.cs
> +        public void GetSafetlyTypes_Given_Types_With_Not_Null_Assembly()
Suggestion: Same as above

2020-10-20 12:52 UTC, wintondeshong commented on test/AndcultureCode.CSharp.Extensions.Tests/AssemblyExtensionsTest.cs
> +        public void GetSafetlyTypes_Given_Types_With_Domain_Assemblies()
Suggestion: Same as above

2020-10-20 12:52 UTC, wintondeshong commented on test/AndcultureCode.CSharp.Extensions.Tests/AssemblyExtensionsTest.cs
> +                    classes: new List<Type> { this.GetType() }.ToArray(),
Suggestion: Recommend just initializing `Type[]` instead of a List which is immediately converted to an array

```csharp
new Type[] { this.GetType() }
```

2020-10-20 12:52 UTC, wintondeshong commented on test/AndcultureCode.CSharp.Extensions.Tests/AssemblyExtensionsTest.cs
> +}
Nitpick: Newline at end of file

2020-10-20 12:52 UTC, wintondeshong commented on test/AndcultureCode.CSharp.Extensions.Tests/AssemblyExtensionsTest.cs
> +        #endregion
Nitpick: We have been following the convention of copying the region name after the corresponding endregion

```csharp
#endregion Exception failures
```

2020-10-20 17:51 UTC, dzoccarato commented on src/AndcultureCode.CSharp.Extensions/AssemblyExtension.cs
> +            if(assembly == null)
resolved in: https://github.com/AndcultureCode/AndcultureCode.CSharp.Extensions/pull/46/commits/419143952c5f2728084ec84bc63526af50c6224a

2020-10-20 17:51 UTC, dzoccarato commented on test/AndcultureCode.CSharp.Extensions.Tests/AssemblyExtensionsTest.cs
> +        public void GetSafetlyTypes_Given_Empty_Type_With_Null_Assembly()
should resolved in: https://github.com/AndcultureCode/AndcultureCode.CSharp.Extensions/pull/46/commits/936dd39256fbf34760f330347d008ddda3bcd044

2020-10-20 17:51 UTC, dzoccarato commented on test/AndcultureCode.CSharp.Extensions.Tests/AssemblyExtensionsTest.cs
> +        public void GetSafetlyTypes_Given_Types_With_Not_Null_Assembly()
should resolved in: https://github.com/AndcultureCode/AndcultureCode.CSharp.Extensions/pull/46/commits/936dd39256fbf34760f330347d008ddda3bcd044

2020-10-20 17:51 UTC, dzoccarato commented on test/AndcultureCode.CSharp.Extensions.Tests/AssemblyExtensionsTest.cs
> +        public void GetSafetlyTypes_Given_Types_With_Domain_Assemblies()
should resolved in: https://github.com/AndcultureCode/AndcultureCode.CSharp.Extensions/pull/46/commits/936dd39256fbf34760f330347d008ddda3bcd044

2020-10-20 17:52 UTC, dzoccarato commented on test/AndcultureCode.CSharp.Extensions.Tests/AssemblyExtensionsTest.cs
> +                    classes: new List<Type> { this.GetType() }.ToArray(),
resolved in: https://github.com/AndcultureCode/AndcultureCode.CSharp.Extensions/pull/46/commits/43f3e493a8a217e6e8cc5577cddb2d383af1b4b6

2020-10-20 17:52 UTC, dzoccarato commented on test/AndcultureCode.CSharp.Extensions.Tests/AssemblyExtensionsTest.cs
> +}
resolved in: https://github.com/AndcultureCode/AndcultureCode.CSharp.Extensions/pull/46/commits/fc25b26a852ab7b960cdcc1d399df06eb74fb243

2020-10-20 17:52 UTC, dzoccarato commented on test/AndcultureCode.CSharp.Extensions.Tests/AssemblyExtensionsTest.cs
> +        #endregion
resolved in: https://github.com/AndcultureCode/AndcultureCode.CSharp.Extensions/pull/46/commits/cf29aa101a4e279a914004547e67ab38d0b249da

2020-10-20 17:53 UTC, dzoccarato commented
Hi @wintondeshong , thanks for your feedback! I've updated this PR with changes you request.

2020-10-29 16:33 UTC, brandongregoryscott requested changes
@dzoccarato Left some feedback for cleanup. Let me know when it is ready for another pass, thank you!

2020-10-29 16:33 UTC, brandongregoryscott commented on test/AndcultureCode.CSharp.Extensions.Tests/AssemblyExtensionsTest.cs
> +        #region NullAssembly
For regions in tests, we typically just start with one region for the method being tested. If there are multiple overloads, we'll add some additional context for which overload is being tested.For something with only a few test cases like this, I don't think there's much benefit into each test or two having its own region.

2020-10-29 16:33 UTC, brandongregoryscott commented on test/AndcultureCode.CSharp.Extensions.Tests/AssemblyExtensionsTest.cs
> +            var types = assembly.GetSafetlyTypes(); // act
Nitpick - capitalization, and a missing `Arrange` step. I would prefer to keep those on separate lines before the actual function calls, ie:

```CS
// Arrange
var assembly = Assembly.GetExecutingAssembly();

// Act
var result = assembly.GetLoadableTypes();

// Assert
result.ShouldNotBeEmpty();
```

2020-10-29 16:33 UTC, brandongregoryscott commented on test/AndcultureCode.CSharp.Extensions.Tests/AssemblyExtensionsTest.cs
> +        internal class AssemblyFailure_ReflectionTypeLoadException : Assembly
Once the other regions are collapsed, this is one that could belong on its own, in a `Setup` region. Easier to catch at a glance when it is at the top of the file and in your face.

2020-10-29 18:18 UTC, dzoccarato commented
@brandongregoryscott , thanks for your feedback! Should fixed now, let me know, thanks!

2020-10-29 20:09 UTC, brandongregoryscott requested changes
Thanks for the quick turn around @dzoccarato 👍 Just a few suggestions for the naming of the tests & a region tag. Looks all good aside from that!

2020-10-29 20:09 UTC, brandongregoryscott commented on test/AndcultureCode.CSharp.Extensions.Tests/AssemblyExtensionsTest.cs
> +        #endregion
Nitpick: please update this endregion tag to match its starting tag, `Setup`

2020-10-29 20:09 UTC, brandongregoryscott commented on test/AndcultureCode.CSharp.Extensions.Tests/AssemblyExtensionsTest.cs
> +        public void GetLoadableTypes_Returns_Empty_Type_List_With_Null_Assembly()
For test naming, we try to adhere to [Given/When/Then](https://martinfowler.com/bliki/GivenWhenThen.html) - this would probably read better as `GetLoadableTypes_When_Assembly_Null_Returns_Empty_List`

2020-10-29 20:09 UTC, brandongregoryscott commented on test/AndcultureCode.CSharp.Extensions.Tests/AssemblyExtensionsTest.cs
> +        public void GetLoadableTypes_Returns_Not_Empty_Type_List_With_Not_Null_Assembly()
`GetLoadableTypes_When_Assembly_Valid_Returns_List_With_Values()`

2020-10-29 20:09 UTC, brandongregoryscott commented on test/AndcultureCode.CSharp.Extensions.Tests/AssemblyExtensionsTest.cs
> +        public void GetLoadableTypes_Given_Types_From_Exception()
`GetLoadableTypes_When_Assembly_Throws_Returns_Empty_List`

2020-10-29 20:09 UTC, brandongregoryscott commented on test/AndcultureCode.CSharp.Extensions.Tests/AssemblyExtensionsTest.cs
> +        public void GetLoadableTypes_Given_Types_From_ReflectionTypeLoadException()
`GetLoadableTypes_When_ReflectionTypeLoadException_Thrown_Returns_Successfully_Loaded_Types`

2020-10-29 20:27 UTC, dzoccarato commented
Hi @brandongregoryscott ! updated according your suggestions!

2020-10-29 23:16 UTC, brandongregoryscott approved these changes

2020-10-29 23:18 UTC, merged

2020-10-29 23:18 UTC, brandongregoryscott commented
Thanks @dzoccarato!